name: MSBuild

on: [push]

env:
  PLATFORM: x86

jobs:
  Release_build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{env.PLATFORM}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild Custom-NL-Means-Light-GPU.sln /m /t:rebuild /p:Configuration=${{env.CONFIGURATION}}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Custom-NL-Means-Light-GPU_Release
          path: Release

  Debug_build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Debug

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{env.PLATFORM}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild Custom-NL-Means-Light-GPU.sln /m /t:rebuild /p:Configuration=${{env.CONFIGURATION}}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Custom-NL-Means-Light-GPU_Debug
          path: Debug
